[package]
name = "wallet_signer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.2"
ic-cdk = "0.12.1"
ic-cdk-macros = "0.8.1"
serde = "1.0.190"
serde_cbor = "0.11.2"
junobuild-satellite = { version = "0.0.17", default-features = false }
junobuild-macros = "0.0.2"
junobuild-utils = "0.0.1"

